# Generated by Django 6.0.4 on 2026-05-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon_order_discount_amount_order_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('failed', 'لغو شده')], default='pending', max_length=20),
        ),
    ]
